# Project to clone a Git repository to a local directory and copy manifests to /tmp/local-docker-install and /tmp/sample-docker-app
---
apiVersion: v1-alpha
kind: GitManifestLocation 
metadata:
  name: clone-repositories-manifests
spec:
  location: https://github.com/nicc777/verba-cratis-test-projects.git
  relative_start_directory: /clone-repositories-project 
---
apiVersion: v1-alpha
kind: Project
metadata:
  name: clone-repositories-project
  environments:
  - default
spec:
  locations:
  - clone-repositories-manifests


# Project to install Docker on the local machine
---
apiVersion: v1-alpha
kind: LocalDirectoryManifestLocation
metadata:
  name: local-docker-install-manifests
spec:
  include_file_regex: .*\.yml|.*\.yaml
  location: /tmp/local-docker-install
---
apiVersion: v1-alpha
kind: Project
metadata:
  name: local-docker-install-project
  environments:
  - default
spec:
  locations:
  - local-docker-install-manifests
  parentProjects:
  - clone-repositories-project


# Install a sample app
---
apiVersion: v1-alpha
kind: LocalDirectoryManifestLocation
metadata:
  name: sample-install-manifests
spec:
  include_file_regex: .*\.yml|.*\.yaml
  location: /tmp/sample-docker-app
---
apiVersion: v1-alpha
kind: Project
metadata:
  name: hello-world-project
  environments:
  - default
spec:
  locations:
  - sample-install-manifests
  parentProjects:
  - local-docker-install-project



